name: github-pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Pull Submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.11
      with:
        hugo-version: '0.70.0'

    - name: Build Blog
      run: hugo --gc --minify

    - name: Deploy Blog
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} 
        publish_dir: ./public
